# Utilise une image Node.js officielle
FROM node:23-slim

# Définit le répertoire de travail dans le conteneur
WORKDIR /app

# Copie les fichiers package.json et package-lock.json
COPY package*.json ./

# Installe les dépendances
RUN npm install

# Copie le reste des fichiers de l'application
COPY . .

# Expose le port utilisé par l'application (modifie si besoin)
EXPOSE 3000

# Commande pour lancer l'application en mode développement
CMD ["npm", "run", "dev"]